### ISSUE TITLE
HCICollector run within kubernetes clusters

### ISSUE THREAD

**Issue by arunbpt7** [scaleoutsean/hcicollector#13]
Hello ,

Just want to check if the HCI collector can be run as resources within kubernetes.
i

**Comment by scaleoutsean** [comment]
Yes, it's possible, we'd just need one container ([sfcollector](https://github.com/scaleoutsean/hcicollector/tree/v0.7/sfcollector)) with appropriate config files (to send to existing Grafana in K8s), and then load dashboards or create own. Because sfcollector now uses Graphite, we'd also need to add a Graphite container and then in Grafana add that Graphite back-end.

Or, we could make the entire stack run on K8s on its own (but that would create two places to monitor infra, one for K8s built-in metrics, and another for SF/HCI), so this is less involved but may be also harder to use. 
It depends on use case - if "IT infra" watches and maintains underlying infrastructure and K8s people watch apps running in VMs, for example, this could be acceptable.

**Comment by arunbpt7** [comment]
it would be really great if you can  help to prepare the first plan in details.

**Comment by scaleoutsean** [comment]
I'll keep this open for the time I can do something about it. 

Meanwhile take a look at https://github.com/mjavier2k/solidfire-exporter, it looks quite good!

**Comment by arunbpt7** [comment]
@scaleoutsean , currious to know , are these tools (HCI collector and Solidfire-exporter) from netapp ? 
if yes , is it possible to move them to the netapp offcial  github. It would steamline the open source images/repos proccurement process in the firm , otherwise it would go through different process and explanations.

**Comment by scaleoutsean** [comment]
They aren't from NetApp. I happen to work there but it's a personal project. I don't know who the SolidFire Exporter author is.

Some Github projects that have monitoring features (eg there is an InfluxDB/Grafana project for E-Series) are managed by NetApp, but this one is personal.

**Comment by scaleoutsean** [comment]
A container that's easy to run has been posted to https://hub.docker.com/repository/docker/scaleoutsean/sfc.
`scaleoutsean/sfc:v0.7` works with Dashboards from [the same release](https://github.com/scaleoutsean/hcicollector/tree/v0.7/grafana/dashboards), as long as they're not vSphere dashboards (it only collects SolidFire metrics).
If Graphite and SolidFire Collector are in the same deployment, just add something like this to it. Otherwise create a new deployment and use IPv4 of Graphite sever.
```yaml
     - image: docker.io/scaleoutsean/sfc:v0.7
       name: sfc
       args: [ "-s", "$(SF_MVIP)", "-u", "$(SF_RO_ADMIN)", "-p", "$(SF_RO_ADMIN_PASS)", "-g", "$(GRAPHITE_TARGET)" ]
       env:
         - name: SF_MVIP
           value: "192.168.1.30"
         - name: SF_RO_ADMIN
           value: "sfc"
         - name: SF_RO_ADMIN_PASS
           value: "*****"
         - name: GRAPHITE_TARGET
           value: "localhost"
```
